version: "3.8"

services:
  api1:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api1
    environment:
      PORT: 3000
      DATABASE_URL: postgres://rinha:rinha@db:5432/rinha
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "190MB"

  api2:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api2
    environment:
      PORT: 3000
      DATABASE_URL: postgres://rinha:rinha@db:5432/rinha
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "190MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "30MB"

  db:
    image: postgres:16
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "140MB"