version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1.0GB
